### ISSUE TITLE
How to control the state of the gripper?

### ISSUE THREAD

**Issue by Steven-xzr** [PaulPauls/franka_emika_panda_pybullet#1]
Hi there! I've noticed there is an `include_gripper` option in the `PandaRobot` class, but how can I control the state (i.e., open or close) of the gripper in the manipulation process? Could you provide an example?

**Comment by PaulPauls** [comment]
Hi Steven,

I unfortunately don't know how to control the gripper when included. I am not an expert in pybullet and solely used the robot simulation for joint inverse dynamics calculation either including or excluding the gripper for weight consideration. The robot model itself I have found on the Franka Emika ROS github repository (linked in the README) and then simply converted to pybullet compatible urdf.

If you find out how to do it let me know and I'll include it in the code for others to profit as well.

Cheers.

**Comment by Steven-xzr** [comment]
Hi Paul,

I start to use the AiRobot library [https://airobot.readthedocs.io/en/latest/airobot/README.html](url) these days. This library provides friendly API to control the pose of the end effector, as well as the open/close status. While I meet with some bugs when I try to initialize multiple robots, this library is largely good-quality and worth a try :)
